version: '3.3'
services:

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: cc_webserver
        restart: unless-stopped
        tty: true
        ports:
            - '81:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app

    #App Service
    app:
        image: cc_image
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: cc_app
        restart: unless-stopped
        environment:
            CONTAINER_ROLE: app
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            APP_ENV: production
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/php.ini
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
            - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
        depends_on:
            - db

    # PgSQL
    db:
        image: postgres:14
        restart: always
        container_name: cc_db
        ports:
            - '5460:5432'
        environment:
            POSTGRES_DB: 'cc_dd'
            POSTGRES_USER: 'cc_user'
            POSTGRES_PASSWORD: 'cc_password'
        volumes:
            - 'cc_volume:/var/lib/postgresql/data'

    redis:
        image: redis:4.0
        container_name: cc_redis
        ports:
            - "6361:6379"
        volumes:
            - "cc_redis_volume:/data"

#Volumes
volumes:
    cc_volume:
    cc_pgadmin_volume:
    cc_redis_volume:

networks:
    cc_network:
        driver: bridge
